/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CompareUniversitiesRouteImport } from './routes/compare-universities'
import { Route as BestOnlineProgramRouteImport } from './routes/best-online-$program'
import { Route as AmityOnlineScholarshipRouteImport } from './routes/amity-online-scholarship'
import { Route as AmityOnlineReviewRouteImport } from './routes/amity-online-review'
import { Route as AmityOnlinePlacementRouteImport } from './routes/amity-online-placement'
import { Route as AmityOnlineFeesRouteImport } from './routes/amity-online-fees'
import { Route as AmityOnlineEligibilityRouteImport } from './routes/amity-online-eligibility'
import { Route as AmityOnlineCoursesRouteImport } from './routes/amity-online-courses'
import { Route as AmityOnlineAdmissionLastDateRouteImport } from './routes/amity-online-admission-last-date'
import { Route as AmityOnlineAdmissionRouteImport } from './routes/amity-online-admission'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareUniversitiesRoute = CompareUniversitiesRouteImport.update({
  id: '/compare-universities',
  path: '/compare-universities',
  getParentRoute: () => rootRouteImport,
} as any)
const BestOnlineProgramRoute = BestOnlineProgramRouteImport.update({
  id: '/best-online-$program',
  path: '/best-online-$program',
  getParentRoute: () => rootRouteImport,
} as any)
const AmityOnlineScholarshipRoute = AmityOnlineScholarshipRouteImport.update({
  id: '/amity-online-scholarship',
  path: '/amity-online-scholarship',
  getParentRoute: () => rootRouteImport,
} as any)
const AmityOnlineReviewRoute = AmityOnlineReviewRouteImport.update({
  id: '/amity-online-review',
  path: '/amity-online-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AmityOnlinePlacementRoute = AmityOnlinePlacementRouteImport.update({
  id: '/amity-online-placement',
  path: '/amity-online-placement',
  getParentRoute: () => rootRouteImport,
} as any)
const AmityOnlineFeesRoute = AmityOnlineFeesRouteImport.update({
  id: '/amity-online-fees',
  path: '/amity-online-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const AmityOnlineEligibilityRoute = AmityOnlineEligibilityRouteImport.update({
  id: '/amity-online-eligibility',
  path: '/amity-online-eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AmityOnlineCoursesRoute = AmityOnlineCoursesRouteImport.update({
  id: '/amity-online-courses',
  path: '/amity-online-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AmityOnlineAdmissionLastDateRoute =
  AmityOnlineAdmissionLastDateRouteImport.update({
    id: '/amity-online-admission-last-date',
    path: '/amity-online-admission-last-date',
    getParentRoute: () => rootRouteImport,
  } as any)
const AmityOnlineAdmissionRoute = AmityOnlineAdmissionRouteImport.update({
  id: '/amity-online-admission',
  path: '/amity-online-admission',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amity-online-admission': typeof AmityOnlineAdmissionRoute
  '/amity-online-admission-last-date': typeof AmityOnlineAdmissionLastDateRoute
  '/amity-online-courses': typeof AmityOnlineCoursesRoute
  '/amity-online-eligibility': typeof AmityOnlineEligibilityRoute
  '/amity-online-fees': typeof AmityOnlineFeesRoute
  '/amity-online-placement': typeof AmityOnlinePlacementRoute
  '/amity-online-review': typeof AmityOnlineReviewRoute
  '/amity-online-scholarship': typeof AmityOnlineScholarshipRoute
  '/best-online-$program': typeof BestOnlineProgramRoute
  '/compare-universities': typeof CompareUniversitiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fees': typeof FeesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amity-online-admission': typeof AmityOnlineAdmissionRoute
  '/amity-online-admission-last-date': typeof AmityOnlineAdmissionLastDateRoute
  '/amity-online-courses': typeof AmityOnlineCoursesRoute
  '/amity-online-eligibility': typeof AmityOnlineEligibilityRoute
  '/amity-online-fees': typeof AmityOnlineFeesRoute
  '/amity-online-placement': typeof AmityOnlinePlacementRoute
  '/amity-online-review': typeof AmityOnlineReviewRoute
  '/amity-online-scholarship': typeof AmityOnlineScholarshipRoute
  '/best-online-$program': typeof BestOnlineProgramRoute
  '/compare-universities': typeof CompareUniversitiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fees': typeof FeesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amity-online-admission': typeof AmityOnlineAdmissionRoute
  '/amity-online-admission-last-date': typeof AmityOnlineAdmissionLastDateRoute
  '/amity-online-courses': typeof AmityOnlineCoursesRoute
  '/amity-online-eligibility': typeof AmityOnlineEligibilityRoute
  '/amity-online-fees': typeof AmityOnlineFeesRoute
  '/amity-online-placement': typeof AmityOnlinePlacementRoute
  '/amity-online-review': typeof AmityOnlineReviewRoute
  '/amity-online-scholarship': typeof AmityOnlineScholarshipRoute
  '/best-online-$program': typeof BestOnlineProgramRoute
  '/compare-universities': typeof CompareUniversitiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fees': typeof FeesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amity-online-admission'
    | '/amity-online-admission-last-date'
    | '/amity-online-courses'
    | '/amity-online-eligibility'
    | '/amity-online-fees'
    | '/amity-online-placement'
    | '/amity-online-review'
    | '/amity-online-scholarship'
    | '/best-online-$program'
    | '/compare-universities'
    | '/disclaimer'
    | '/fees'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amity-online-admission'
    | '/amity-online-admission-last-date'
    | '/amity-online-courses'
    | '/amity-online-eligibility'
    | '/amity-online-fees'
    | '/amity-online-placement'
    | '/amity-online-review'
    | '/amity-online-scholarship'
    | '/best-online-$program'
    | '/compare-universities'
    | '/disclaimer'
    | '/fees'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/amity-online-admission'
    | '/amity-online-admission-last-date'
    | '/amity-online-courses'
    | '/amity-online-eligibility'
    | '/amity-online-fees'
    | '/amity-online-placement'
    | '/amity-online-review'
    | '/amity-online-scholarship'
    | '/best-online-$program'
    | '/compare-universities'
    | '/disclaimer'
    | '/fees'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/courses/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmityOnlineAdmissionRoute: typeof AmityOnlineAdmissionRoute
  AmityOnlineAdmissionLastDateRoute: typeof AmityOnlineAdmissionLastDateRoute
  AmityOnlineCoursesRoute: typeof AmityOnlineCoursesRoute
  AmityOnlineEligibilityRoute: typeof AmityOnlineEligibilityRoute
  AmityOnlineFeesRoute: typeof AmityOnlineFeesRoute
  AmityOnlinePlacementRoute: typeof AmityOnlinePlacementRoute
  AmityOnlineReviewRoute: typeof AmityOnlineReviewRoute
  AmityOnlineScholarshipRoute: typeof AmityOnlineScholarshipRoute
  BestOnlineProgramRoute: typeof BestOnlineProgramRoute
  CompareUniversitiesRoute: typeof CompareUniversitiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FeesRoute: typeof FeesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-universities': {
      id: '/compare-universities'
      path: '/compare-universities'
      fullPath: '/compare-universities'
      preLoaderRoute: typeof CompareUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-online-$program': {
      id: '/best-online-$program'
      path: '/best-online-$program'
      fullPath: '/best-online-$program'
      preLoaderRoute: typeof BestOnlineProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amity-online-scholarship': {
      id: '/amity-online-scholarship'
      path: '/amity-online-scholarship'
      fullPath: '/amity-online-scholarship'
      preLoaderRoute: typeof AmityOnlineScholarshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amity-online-review': {
      id: '/amity-online-review'
      path: '/amity-online-review'
      fullPath: '/amity-online-review'
      preLoaderRoute: typeof AmityOnlineReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amity-online-placement': {
      id: '/amity-online-placement'
      path: '/amity-online-placement'
      fullPath: '/amity-online-placement'
      preLoaderRoute: typeof AmityOnlinePlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amity-online-fees': {
      id: '/amity-online-fees'
      path: '/amity-online-fees'
      fullPath: '/amity-online-fees'
      preLoaderRoute: typeof AmityOnlineFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amity-online-eligibility': {
      id: '/amity-online-eligibility'
      path: '/amity-online-eligibility'
      fullPath: '/amity-online-eligibility'
      preLoaderRoute: typeof AmityOnlineEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amity-online-courses': {
      id: '/amity-online-courses'
      path: '/amity-online-courses'
      fullPath: '/amity-online-courses'
      preLoaderRoute: typeof AmityOnlineCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amity-online-admission-last-date': {
      id: '/amity-online-admission-last-date'
      path: '/amity-online-admission-last-date'
      fullPath: '/amity-online-admission-last-date'
      preLoaderRoute: typeof AmityOnlineAdmissionLastDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amity-online-admission': {
      id: '/amity-online-admission'
      path: '/amity-online-admission'
      fullPath: '/amity-online-admission'
      preLoaderRoute: typeof AmityOnlineAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmityOnlineAdmissionRoute: AmityOnlineAdmissionRoute,
  AmityOnlineAdmissionLastDateRoute: AmityOnlineAdmissionLastDateRoute,
  AmityOnlineCoursesRoute: AmityOnlineCoursesRoute,
  AmityOnlineEligibilityRoute: AmityOnlineEligibilityRoute,
  AmityOnlineFeesRoute: AmityOnlineFeesRoute,
  AmityOnlinePlacementRoute: AmityOnlinePlacementRoute,
  AmityOnlineReviewRoute: AmityOnlineReviewRoute,
  AmityOnlineScholarshipRoute: AmityOnlineScholarshipRoute,
  BestOnlineProgramRoute: BestOnlineProgramRoute,
  CompareUniversitiesRoute: CompareUniversitiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  FeesRoute: FeesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
