/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CompareUniversitiesRouteImport } from './routes/compare-universities'
import { Route as BestOnlineProgramRouteImport } from './routes/best-online-$program'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'

const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareUniversitiesRoute = CompareUniversitiesRouteImport.update({
  id: '/compare-universities',
  path: '/compare-universities',
  getParentRoute: () => rootRouteImport,
} as any)
const BestOnlineProgramRoute = BestOnlineProgramRouteImport.update({
  id: '/best-online-$program',
  path: '/best-online-$program',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-online-$program': typeof BestOnlineProgramRoute
  '/compare-universities': typeof CompareUniversitiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fees': typeof FeesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-online-$program': typeof BestOnlineProgramRoute
  '/compare-universities': typeof CompareUniversitiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fees': typeof FeesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-online-$program': typeof BestOnlineProgramRoute
  '/compare-universities': typeof CompareUniversitiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fees': typeof FeesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best-online-$program'
    | '/compare-universities'
    | '/disclaimer'
    | '/fees'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best-online-$program'
    | '/compare-universities'
    | '/disclaimer'
    | '/fees'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/best-online-$program'
    | '/compare-universities'
    | '/disclaimer'
    | '/fees'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-conditions'
    | '/courses/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestOnlineProgramRoute: typeof BestOnlineProgramRoute
  CompareUniversitiesRoute: typeof CompareUniversitiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FeesRoute: typeof FeesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-universities': {
      id: '/compare-universities'
      path: '/compare-universities'
      fullPath: '/compare-universities'
      preLoaderRoute: typeof CompareUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-online-$program': {
      id: '/best-online-$program'
      path: '/best-online-$program'
      fullPath: '/best-online-$program'
      preLoaderRoute: typeof BestOnlineProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestOnlineProgramRoute: BestOnlineProgramRoute,
  CompareUniversitiesRoute: CompareUniversitiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  FeesRoute: FeesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
